//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace проектная_работа.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class sportsman
    {
        public int id { get; set; }
        public string citizenship { get; set; }
        public double height { get; set; }
        public double foot { get; set; }
        public int human { get; set; }
        public double weight { get; set; }
    
        public virtual human human1 { get; set; }
    }
}
