//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace проектная_работа.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int userType { get; set; }
        public int human { get; set; }
        public string image { get; set; }
    
        public virtual human human1 { get; set; }
        public virtual UserType UserType1 { get; set; }
    }
}
